---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tathluac/public_html
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp portfolio.html $DEPLOYPATH
    - /bin/cp qualifications.html $DEPLOYPATH
    - /bin/cp free.css $DEPLOYPATH
    - /bin/cp strict.css $DEPLOYPATH
    - /bin/cp switch-modes.js $DEPLOYPATH
    - /bin/cp altbackground.png $DEPLOYPATH
    - /bin/cp background.png $DEPLOYPATH
    - /bin/cp github.png $DEPLOYPATH
    - /bin/cp home_button.png $DEPLOYPATH
    - /bin/cp linkedin.png $DEPLOYPATH
    - /bin/cp portfolio_button_small.png $DEPLOYPATH
    - /bin/cp portfolio_button.png $DEPLOYPATH
    - /bin/cp qualifications_button.png $DEPLOYPATH
    - /bin/cp resume.png $DEPLOYPATH
    - /bin/cp switchtofree.png $DEPLOYPATH
    - /bin/cp switchtostrict.png $DEPLOYPATH
    - /bin/cp tath_main.png $DEPLOYPATH
    - /bin/cp resume.pdf $DEPLOYPATH